-- SQLite
-- Exibindo dados das locações, com nome do cliente, automóvel
-- e funcionários vinculados

SELECT LOC.START_DATE AS START_DATE, LOC.END_DATE AS END_DATE, LOC.TOTAL AS TOTAL,
    CUST.NAME AS CUSTOMER_NAME, CARS.NAME AS CAR_NAME, EMP.NAME AS EMPLOYEE_NAME
    FROM LOCATIONS LOC
    JOIN CUSTOMERS CUST ON (LOC.CUSTOMER_ID = CUST.ID)
    JOIN CARS ON (LOC.CAR_ID = CARS.ID)
    JOIN EMPLOYEES EMP ON (LOC.EMPLOYEE_ID = EMP.ID);